### ISSUE TITLE
hw use https://github.com/yangwuan55/ExoPlayer

### ISSUE THREAD

**Issue by nzala** [yangwuan55/common-android#3]
hw use

**Comment by yangwuan55** [comment]
[https://github.com/yangwuan55/ExoPlayer/tree/playbackSpeed/demo_speed](url)
Please see this demo.

**Comment by nzala** [comment]
link bken

**Comment by yangwuan55** [comment]
https://github.com/yangwuan55/ExoPlayer/tree/playbackSpeed/demo_speed
